hash-format = "sha256"

[[files]]
file = "config/yosbr/config/bountiful/bountiful.json"

[[files]]
file = "config/yosbr/config/iris.properties"

[[files]]
file = "config/yosbr/config/universal-graves/config.json"

[[files]]
file = "config/yosbr/config/universal-graves/models/example.json"

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
metafile = true

[[files]]
file = "mods/bclib.pw.toml"
metafile = true

[[files]]
file = "mods/betterend.pw.toml"
metafile = true

[[files]]
file = "mods/betternether.pw.toml"
metafile = true

[[files]]
file = "mods/bountiful.pw.toml"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
metafile = true

[[files]]
file = "mods/cyberanner-ironchest.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/immersiveportals.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/kambrik.pw.toml"
metafile = true

[[files]]
file = "mods/origins.pw.toml"
metafile = true

[[files]]
file = "mods/pandas-falling-trees.pw.toml"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
metafile = true

[[files]]
file = "mods/rpg-origins.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/touhou-origins.pw.toml"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
metafile = true

[[files]]
file = "mods/wakes.pw.toml"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
metafile = true

[[files]]
file = "mods/wwoo.pw.toml"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/ยง9AVPBR+Retextured+R2.zip"

[[files]]
file = "shaderpacks/ComplementaryReimagined_r2.2.1.zip"
