name = "Manticore"
author = "aeases, raptoraxe"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5411ad09440c782131fe183408c5c872673744d1b237080b3f132af595b6eaf"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
