name = "Manticore"
author = "aeases, raptoraxe"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43fee53e9a1214e06c26c340ae0f31c9e68a996c166e90f47f08a6c76c6dc323"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
