name = "Manticore"
author = "aeases, raptoraxe"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccee4e30f079dd9e9fad451744e291091f86c99a8808580c3b7d0ff3390f7a4b"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
